CC=g++

all: p1 p2 p3 p4 p5

p1: p1.cpp
		$(CC) -o p1 p1.cpp

p2: p2.cpp
		$(CC) -o p2 p2.cpp

p3: p3.cpp
		$(CC) -o p3 p3.cpp

p4: p4.cpp
		$(CC) -o p4 p4.cpp

p5: p5.cpp
		$(CC) -o p5 p5.cpp


clean:
	@echo "Cleaning...."
	rm -rf a.out p1 p2 p3 p4
	rm -rf p5